config/routes.rb
Rails.application.routes.draw do
root 'restaurants#index'

  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:show, :new, :create]
  end

  resources :reviews, only: [:index, :show, :new, :create]
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews

  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  RATINGS = [
    1,
    2,
    3,
    4,
    5
  ]

  belongs_to :restaurant

  validates :rating, presence: true, inclusion: { in: RATINGS }
  validates :body, presence: true
  validates_presence_of :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = 'Restaurant added!'
      redirect_to @restaurant
    else
      flash[:alert] = 'Restaurant not added!'
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :state, :zipcode, :description, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # def show
  #   @review = Review.find(params[:id])
  # end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    # @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant_id = params[:restaurant_id]
    if @review.save
      flash[:notice] = "Review saved. Hopefully it was nice!"
      redirect_to restaurant_path(params[:restaurant_id])
    else
      flash[:alert]  = "Review not saved"
      redirect_to restaurant_path(params[:restaurant_id])
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Good Eats</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container">

      <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
          <li class="name">
            <h1><%= link_to "As Good As It Gets", root_path %></h1>
          </li>
        </ul>
      </nav>

    <% if notice %>
      <div class="notice"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert"><%= alert %></div>
    <% end %>

    <%= yield %>

    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="show_name">
  Restaurants
</div>

<dl class="sub-nav">
  <dd><%= link_to 'Add a new restaurant', new_restaurant_path %></dd>
</dl>

<fieldset>
  <div class="restaurants">
  <% @restaurants.each do |restaurant| %>
    <div class="restaurants panel">
      <div class="r_name"><%= 'Restaurant: ' %><%= link_to restaurant.name, restaurant_path(restaurant) %></div>
      <div class="r_add"><%= 'Address: ' %><%= restaurant.address %></div>
      <div class="r_city"><%= 'City: ' %><%= restaurant.city %></div>
      <div class="r_state"><%= 'State: ' %><%= restaurant.state %></div>
      <div class="r_zip"><%= 'Zip Code: ' %><%= restaurant.zipcode %></div>
      <div class="r_des"><%= 'Description: ' %><%= restaurant.description %></div>
      <div class="r_cat"><%= 'Category: ' %><%= restaurant.category %></div>
    </div>
  <% end %>
  </div>
</fieldset>

app/views/restaurants/new.html.erb
<div class="title_header">
  Let's add a fantastic restaurant, shall we?
</div>

<fieldset>
  <%= form_for @restaurant do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div>
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

    <%= f.submit "Bon Apetit!" %>
  <% end %>
</fieldset>

app/views/restaurants/show.html.erb
<div class="show_name">
  <%= @restaurant.name %>
</div>

<fieldset>
<div class="show_description">
  <p><%= 'Description: ' %><%= @restaurant.description %></p>
  <p><%= 'Category: ' %><%= @restaurant.category %></p>
</div>

<div class="show_address">
  <%= @restaurant.address %>
  <%= @restaurant.city %><%= ', '%><%= @restaurant.state %><%= '  ' %><%= @restaurant.zipcode %>
</div>

<div class="write_review">
  <%= link_to 'Write a Review', new_restaurant_review_path(@restaurant) %>
</div>

<% if !@review.empty? %>
  <fieldset>
    <legend>Reviews</legend>
      <% @restaurant.reviews.order(created_at: :desc).each do |review| %>
        <div class="reviews panel">
          <p><%= 'Rating: '%><%= review.rating %></p>
          <p><%= review.body %></p>
          <p><%= review.created_at %></p>
        </div>
      <% end %>
  </fieldset>
<% end %>

app/views/reviews/new.html.erb
<div class="title_header">
  Review this fine establishment
</div>

<div class="form">
  <%= form_for [@restaurant, @review] do |f| %>
  <div class="reviews panel">
    <%= f.label :rating %>
    <% Review::RATINGS.each do |rating| %>
      <%= f.radio_button(:rating, rating) %>
      <%= f.label("rating_#{rating}", rating) %>
    <% end %>

    <div class='body'>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>

    <%= f.submit "Post Review" %>
    </div>
  <% end %>
</div>